pipeline{
    agent any

    stages{
        stage('Build'){
            steps{
                dir('sungchef_backend'){
                    dir('sungchef_dummy'){
                        script{
                            sh 'chmod +x gradlew'
                      
                        }
                    }
                }
            }
        }

    }
}