spring:
  application:
    name: recipe-service

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ENC(8nFxIA38P6UrPdchnttu8TZH1GJuwkOS2aK+ARU/ieMJj/BZC+23nS+rAGHtJt3NuEgAcXch2iia/4F/8TWrQQo0NhailLwIb6nNSsDLorOIDTIDpeiugnwlmG39IO5KZtX2iyIwYTUQZF6BAsuFeQvoYg4ybUQG)
    username: ENC(TfuU1Hc9zWv8LfvfBAZZBw==)
    password: ENC(CdQdTRqvHnZXbLGLLzE2X54M10IfeRPDljctYBS3cRI=)

#logging:
#  level:
#    com.ssafy.userservice.client: DEBUG
#    org.hibernate:
#      type.descriptor.sql: trace #show parameter binding
#      SQL: DEBUG


eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
  client:
    register-with-eureka: true
    fetch-registry: true

cloud:
  aws:
    s3:
      bucket: ENC(IGvX0mQjeL6VPtabLU/B3kXnXHsHP9PH)
      base-url: ENC(+kQveyb+VuBLX/CiN6H50l0XtLAHSJv1OzzgTxXJepojkzHq3O3iZRVkEBczjMJeeUb2ddrNxPSh/g+OHoKy2w==)
    credentials:
      access-key: ENC(gcdGAqZv8WsDcz1N6Jo8gdyUVPKcj/tjuKDkDd81CJc=)
      secret-key:  ENC(mzMqMH1luvmBderKnGu4xLA4CNU41hcCMyNZJFsHQIdeATLp5NmC5L5DI4VYbQAAV3h/uEOvulk=)
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

jwt:
  secret:
    ENC(iKUwCClHj209CRLCkRSQ21/darPeFv9UjDUG0/+iX+o0cGedBcHKcvSdp5vO1Pza3UiY0S9WpCkNdQ9kr0V91X2DnwPBy6DaNTHE89Y9L9heGIr+LVJ89A==)