server:
  port: 0
spring:
  application:
    name: fridge-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8762/eureka