# Generated by Django 4.2.11 on 2024-04-02 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suser_sns_id', models.TextField()),
                ('recommend_id', models.IntegerField()),
                ('recommend_type', models.TextField()),
            ],
        ),
    ]
