server:
  port: ${DISCOVERY_PORT}

spring:
  application:
    name: discovery-service
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false